name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install & Build Assets
      run: |
        npm install
        npm run build

    - name: Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/kursusjepangonline.com/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          .env
          phpunit.xml
          README.md
